<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    public const ROLE_ADMIN = 'Admin';
    public const ROLE_PETUGAS = 'Petugas';
    public const ROLE_OWNER = 'Owner';

    /**
     * Custom permissions that aren't tied to Filament Resources/Pages/Widgets.
     *
     * Note: Resource permissions will be generated by `php artisan shield:generate --all`
     * once all Resources/Pages/Widgets exist.
     */
    private const CUSTOM_PERMISSIONS = [
        'Transaksi:Masuk',
        'Transaksi:Keluar',
        'Transaksi:Pembayaran',
        'Transaksi:CetakStruk',
        'Laporan:RekapTransaksi',
        'Pengajuan:Ajukan',
        'Pengajuan:Approve',
    ];

    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $admin = Role::firstOrCreate(['name' => self::ROLE_ADMIN, 'guard_name' => 'web']);
        $petugas = Role::firstOrCreate(['name' => self::ROLE_PETUGAS, 'guard_name' => 'web']);
        $owner = Role::firstOrCreate(['name' => self::ROLE_OWNER, 'guard_name' => 'web']);

        $allPermissions = Permission::query()->where('guard_name', 'web')->pluck('name');

        $customPermissions = collect(self::CUSTOM_PERMISSIONS)
            ->map(fn (string $name) => Permission::firstOrCreate(['name' => $name, 'guard_name' => 'web']))
            ->values();

        // ADMIN
        // - CRUD User, TarifParkir, AreaParkir, Kendaraan
        // - Akses log aktivitas (akan ditambahkan saat ActivityLog Resource/Page dibuat)
        // - Custom transaksi/rekap/pengajuan (opsional)
        $adminPermissionNames = $allPermissions->filter(fn (string $name) => str($name)->startsWith([
            'ViewAny:User', 'View:User', 'Create:User', 'Update:User', 'Delete:User', 'DeleteAny:User', 'Restore:User', 'RestoreAny:User', 'ForceDelete:User', 'ForceDeleteAny:User',
            'ViewAny:TarifParkir', 'View:TarifParkir', 'Create:TarifParkir', 'Update:TarifParkir', 'Delete:TarifParkir', 'DeleteAny:TarifParkir', 'Restore:TarifParkir', 'RestoreAny:TarifParkir', 'ForceDelete:TarifParkir', 'ForceDeleteAny:TarifParkir',
            'ViewAny:AreaParkir', 'View:AreaParkir', 'Create:AreaParkir', 'Update:AreaParkir', 'Delete:AreaParkir', 'DeleteAny:AreaParkir', 'Restore:AreaParkir', 'RestoreAny:AreaParkir', 'ForceDelete:AreaParkir', 'ForceDeleteAny:AreaParkir',
            'ViewAny:Kendaraan', 'View:Kendaraan', 'Create:Kendaraan', 'Update:Kendaraan', 'Delete:Kendaraan', 'DeleteAny:Kendaraan', 'Restore:Kendaraan', 'RestoreAny:Kendaraan', 'ForceDelete:Kendaraan', 'ForceDeleteAny:Kendaraan',
        ]))->values();

        $admin->syncPermissions($adminPermissionNames->merge($customPermissions->pluck('name'))->unique()->all());

        // Petugas: transaksi + cetak struk
        $petugasBase = $customPermissions->whereIn('name', [
            'Transaksi:Masuk',
            'Transaksi:Keluar',
            'Transaksi:Pembayaran',
            'Transaksi:CetakStruk',
        ])->pluck('name');

        $petugasResourcePermissionNames = $allPermissions->filter(fn (string $name) => str($name)->startsWith([
            'ViewAny:Transaksi', 'View:Transaksi', 'Create:Transaksi', 'Update:Transaksi',
            'ViewAny:Shift', 'View:Shift', 'Create:Shift', 'Update:Shift',
        ]))->values();

        $petugas->syncPermissions($petugasResourcePermissionNames->merge($petugasBase)->unique()->all());

        // Owner: rekap + pengajuan (view/approve)
        $ownerBase = $customPermissions->whereIn('name', [
            'Laporan:RekapTransaksi',
            'Pengajuan:Ajukan',
            'Pengajuan:Approve',
        ])->pluck('name');

        $ownerResourcePermissionNames = $allPermissions->filter(fn (string $name) => str($name)->startsWith([
            'ViewAny:Transaksi', 'View:Transaksi',
            'ViewAny:Pengajuan', 'View:Pengajuan', 'Create:Pengajuan', 'Update:Pengajuan',
        ]))->values();

        $owner->syncPermissions($ownerResourcePermissionNames->merge($ownerBase)->unique()->all());

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}

